#!/bin/sh -p

set -eu

readonly SCRIPT_DIRECTORY="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)"
readonly REPOSITORY_ROOT="$(cd -- "$SCRIPT_DIRECTORY/../.." && pwd -P)"

cd -- "$REPOSITORY_ROOT"

export LANG=C
export LC_ALL=C
export SOURCE_DATE_EPOCH=0
export TZ=UTC

exec env \
  -u BASH_ENV \
  -u ENV \
  -u GNUMAKEFLAGS \
  -u MAKEFLAGS \
  -u MAKEFILES \
  -u MAKEOVERRIDES \
  -u MFLAGS \
  make --no-builtin-rules --no-builtin-variables check
